name: Monitorar Preço Steam
on:
  schedule:
    # 15:00 UTC equivale a 12:00 no Horário de Brasília
    - cron: '0 15 * * *'
  workflow_dispatch: # Permite que você rode manualmente para testar

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar o monitor
        env:
          # Conecta os Secrets do GitHub às variáveis do script
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py
